apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c6xogy7c9-go-gitops
  description: This is GitOps manifest for c6xogy7c9-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=c6xogy7c9-go
    backstage.io/kubernetes-id: c6xogy7c9-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: c6xogy7c9-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c6xogy7c9-go
