apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c6xogy7c9-go
  janus-idp.io/tekton: c6xogy7c9-go
  backstage.io/kubernetes-id: c6xogy7c9-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c6xogy7c9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
