apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c6xogy7c9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c6xogy7c9-go 
  name: c6xogy7c9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c6xogy7c9-go 
